from .time import Second, NANOSECOND, MICROSECOND, MILLISECOND


# https://highscalability.com/google-pro-tip-use-back-of-the-envelope-calculations-to-choo/
# https://colin-scott.github.io/personal_website/research/interactive_latency.html
L1_CACHE_LATENCY = 1 * NANOSECOND
BRANCH_MISPREDICT_LATENCY = 3 * NANOSECOND
L2_CACHE_LATENCY = 4 * NANOSECOND
MUTEX_LOCK_UNLOCK_LATENCY = 17 * NANOSECOND
MAIN_MEMORY_LATENCY = 100 * NANOSECOND
READ_1MB_SEQUENTIALLY_FROM_MEMORY_LATENCY = 935 * NANOSECOND
ZIPPY_COMPRESS_1KB_LATENCY = 2 * MICROSECOND
SEND_2KB_BYTES_OVER_1GBPS_LATENCY = 8 * MICROSECOND
READ_1MB_SEQUENTIALLY_FROM_SSD_LATENCY = 15 * MICROSECOND
READ_1MB_SEQUENTIALLY_FROM_DISK_LATENCY = 412 * MICROSECOND
ROUND_TRIP_WITHIN_DC_LATENCY = 500 * MICROSECOND
DISK_SEEK_LATENCY = 2 * MILLISECOND
READ_1MB_FROM_NETWORK_LATENCY = 10 * MILLISECOND

# Send packet CA (California) -> Netherlands -> CA
ROUND_TRIP_PACKET_PST_EU_LATENCY = 150 * MILLISECOND
