from .time import Second, NANOSECOND, MICROSECOND, MILLISECOND


# https://highscalability.com/google-pro-tip-use-back-of-the-envelope-calculations-to-choo/
L1_CACHE_LATENCY = 0.5 * NANOSECOND
BRANCH_MISPREDICT_LATENCY = 5 * NANOSECOND
L2_CACHE_LATENCY = 7 * NANOSECOND
MUTEX_LOCK_UNLOCK_LATENCY = 100 * NANOSECOND
MAIN_MEMORY_LATENCY = 100 * NANOSECOND
ZIPPY_COMPRESS_1KB_LATENCY = 10 * MICROSECOND
SEND_2KB_BYTES_OVER_1GBPS_LATENCY = 20 * MICROSECOND
READ_1MB_SEQUENTIALLY_FROM_MEMORY_LATENCY = 250 * MICROSECOND
ROUND_TRIP_WITHIN_DC_LATENCY = 500 * MICROSECOND
DISK_SEEK_LATENCY = 10 * MICROSECOND
READ_1MB_FROM_NETWORK_LATENCY = 10 * MILLISECOND
READ_1MB_SEQUENTIALLY_FROM_DISK_LATENCY = 30 * MILLISECOND

# Send packet CA (California) -> Netherlands -> CA
ROUND_TRIP_PACKET_PST_EU_LATENCY = 150 * MILLISECOND
