from typing import NewType


Byte = NewType("bytes", int)
BYTE = Byte(1)

BITS_PER_BYTE = 8
BIT = Byte(1 / BITS_PER_BYTE)

BYTES_IN_KILOBYTE = 1000
KILOBYTE = Byte(BYTES_IN_KILOBYTE)

BYTES_IN_MEGABYTE = 1000 * BYTES_IN_KILOBYTE
MEGABYTE = Byte(BYTES_IN_MEGABYTE)

BYTES_IN_GIGABYTE = 1000 * BYTES_IN_MEGABYTE
GIGABYTE = Byte(BYTES_IN_GIGABYTE)

BYTES_IN_PETABYTE = 1000 * BYTES_IN_GIGABYTE
PETABYTE = Byte(BYTES_IN_PETABYTE)
