from typing import NewType


Second = NewType("Second", float)


MILLISECONDS_IN_SECOND = 1000
MICROSECONDS_IN_SECOND = 1000 * MILLISECONDS_IN_SECOND
NANOSECONDS_IN_SECOND = 1000 * MICROSECONDS_IN_SECOND

NANOSECOND = Second(1 / NANOSECONDS_IN_SECOND)
MICROSECOND = Second(1 / MICROSECONDS_IN_SECOND)
MILLISECOND = Second(1 / MILLISECONDS_IN_SECOND)
SECOND = Second(1)

SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR

MINUTE = Second(SECONDS_IN_MINUTE)
HOUR = Second(SECONDS_IN_HOUR)

# Casual time definitions below... just approximations.

HOURS_IN_DAY = 24
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY

DAY = Second(SECONDS_IN_DAY)

DAYS_IN_YEAR = 365.25
SECONDS_IN_YEAR = SECONDS_IN_DAY * DAYS_IN_YEAR

YEAR = Second(SECONDS_IN_YEAR)

MONTHS_IN_YEAR = 12
SECONDS_IN_MONTH = YEAR / MONTHS_IN_YEAR
MONTH = Second(SECONDS_IN_MONTH)

WEEKS_PER_YEAR = DAYS_IN_YEAR / 7
SECONDS_IN_WEEK = YEAR / WEEKS_PER_YEAR
WEEK = Second(SECONDS_IN_WEEK)
