MICROSECONDS_IN_NANOSECOND = 1000
MILLISECONDS_IN_MICROSECOND = 1000
MILLISECONDS_IN_SECOND = 1000
SECONDS_IN_MINUTE = 60
MINUTES_IN_MOUR = 60

NANOSECOND = 1
MICROSECOND = MICROSECONDS_IN_NANOSECOND * NANOSECOND
MILLISECOND = MILLISECONDS_IN_MICROSECOND * MICROSECOND
SECOND = MILLISECONDS_IN_SECOND * MILLISECOND
MINUTE = SECONDS_IN_MINUTE * SECOND
HOUR = MINUTES_IN_MOUR * MINUTE
